version: "3.7"
services:

  traffic-tax-calculator:
    container_name: traffic-tax-calculator
    image: traffic-tax-calculator:latest
    build: .
    restart: always
    ports:
      - "8081:8080"
