server:
  port: 8080

tax-exempted-vehicles:
  vehicles:
    - Motorcycle
    - Bus
    - Emergency
    - Diplomat
    - Military
    - Foreign

time-price:
  time-costs:
    - start-time: "06:00"
      end-time: "06:29"
      price: 8
    - start-time: "06:30"
      end-time: "06:59"
      price: 13
    - start-time: "07:00"
      end-time: "07:59"
      price: 18
    - start-time: "08:00"
      end-time: "08:29"
      price: 13
    - start-time: "08:30"
      end-time: "14:59"
      price: 8
    - start-time: "15:00"
      end-time: "15:29"
      price: 13
    - start-time: "15:30"
      end-time: "16:59"
      price: 18
    - start-time: "17:00"
      end-time: "17:59"
      price: 13
    - start-time: "18:00"
      end-time: "18:29"
      price: 8
    - start-time: "18:30"
      end-time: "05:59"
      price: 0

toll-free-dates:
  years:
    - year: 2013
      months:
        - month: 1
          days: 1
        - month: 3
          days: 28,29
        - month: 4
          days: 1,30
        - month: 5
          days: 1,8,9
        - month: 6
          days: 5,6,21
        - month: 7
        - month: 11
          days: 1
        - month: 12
          days: 24,25,26,31
